### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by PaulJasiul** [jeffochoa/voyager-bread-generator#1]
php artisan hook:install voyager-bread-generator show me error:  Could not find package voyager-bread-generator at any version for your minimum-stability (stable) . Check the package spelling or your minimum-stability.

**Comment by jeffochoa** [comment]
Hi Paul,

Please try with : `php artisan hook:install voyager-bread-generator dev-master`

**Comment by PaulJasiul** [comment]
Thanks. I fixed.
