### ISSUE TITLE
Relationship seeder

### ISSUE THREAD

**Issue by PaulJasiul** [jeffochoa/voyager-bread-generator#2]
I did not find so maybe you can give example how I need to create relationship in my seedee? Also, it will be good if you add documentation for all people.

**Comment by jeffochoa** [comment]
You may want to check the core of the voyager package [https://github.com/the-control-group/voyager/tree/e6af9a284d71f77c7e09a9e7bc27fdad69e5fdeb/publishable/database/seeds](https://github.com/the-control-group/voyager/tree/e6af9a284d71f77c7e09a9e7bc27fdad69e5fdeb/publishable/database/seeds)
